### PR TITLE
Avoid MismatchedInputException when reading KeystoneProject from JSON

### PR DESCRIPTION
**Pull request by taeyeon-Kim**
Avoid MismatchedInputException when reading KeystoneProject from JSON

related to [#1299](https://github.com/ContainX/openstack4j/issues/1299)

### CODE REVIEW

**Comment by olivergondza** [comment]
Thanks, for the proposal. Can you please specify what are the values you are getting instead os `String`? It would be great to take a realistic json payload and create a test verifying it is handled correctly. Also, it is a correct thing to do to ignore other types?

**Comment by taeyeon-Kim** [comment]
@olivergondza amended it. 
`extra` provides properties other than fields defined in `Project`. 
The `extra` type is `Map<String, String>`, so any type other than String should be ignored. 
Then, the issue like [#1299](https://github.com/ContainX/openstack4j/issues/1299) will not be occurred. And deserialization works properly.

**Comment by olivergondza** [comment]
> The extra type is Map<String, String>, so any type other than String should be ignored.

That is specifically what I am disputing. Provided it makes sense to capture those properties, it makes sense doing so even when they are not strings. So the fix I prefer would be to change the property to be of type `Map<String, Object>`.

---

Also, I see the test demonstrates the new functionality (which is great), but it is not *realistic* openstack payload. What is it what the openstack returns for you exactly? Which extra fields does it serve?

**Comment by taeyeon-Kim** [comment]
>  I prefer would be to change the property to be of type Map<String, Object>

I totally agree.
But, `extra` is already in `Map<string, string>`. So, I was worried the users, especially who use those property API, will be affected.


> What is it what the openstack returns for you exactly? Which extra fields does it serve?

In my project, Use extra such as lang, Email, etc...
```json
{
  
  "lang": "ko_KR",
  "email": "${email value}"
 }
```

----------

There was an issue when the version of Openstack4j and openstack keystone were different. For instance, let's assume that my project was changed through CLI since option field has been added from openstack keystone version 16. the below code is the example of my project.

```json
{
  ....
  "options": {},
  ....
 }
```
If there is no option field in the current Openstack4j `keystoneProject`, `MismatchedInputException` will be raised from `public void setExtra(String key, String value)` when objectMapper read project json. 
My original intention (or proposal) was trying to prevent to happen those issues in the future.

**Comment by olivergondza** [comment]
@taeyeon-Kim, most OS4J model objects deals with the fact that openstack4j can be behind openstack version by permitting json keys to be missing from the class (so introducing new keys to api is not going to break client). This concept of extras (provided it really does not accept _everything_) is sort fo rocking the boat there.

So I do not think you should be too worried about the API change.

**Comment by olivergondza** [comment]
@taeyeon-Kim, are you interested in continuing the development here?

**Comment by taeyeon-Kim** [comment]
@olivergondza 
This issue is just an issue created to avoid MismatchedInputException.
If you feel you don't need much, it seems good to close the issue. :)

**Comment by olivergondza** [comment]
True, though there are changes I suggested making before this can be merged. My question is if you are interested in continuing the development.

**Comment by taeyeon-Kim** [comment]
no thanks

**Pull request closed without merging**
