### PR TITLE
  Fix #124:  Entity’s property start with “is” ,causes property dupli…

### LINKED ISSUE #124: Jackson serialization exception
https://github.com/openstack4j/openstack4j/blob/9fca6c8e34f0cc5eed69802880d9e33199910fef/core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronNetQosPolicy.java#L81

That property start with "is" cause a  jackson serialization problem.

https://stackoverflow.com/questions/32270422/jackson-renames-primitive-boolean-field-by-removing-is

### PR DESCRIPTION
**Pull request by fangw1**
Fix #124:  Entity’s property start with “is” ,causes property duplication.

## Submitter checklist
api link: https://docs.openstack.org/api-ref/network/v2/?&expanded=create-qos-policy-detail#qos-policies-qos

### CODE REVIEW

**Comment by olivergondza** [comment]
Thanks, for the contribution. I am adding the submitter checklist that was not filled.

**Comment by bloom-repo** [comment]
> Thanks, for the contribution. I am adding the submitter checklist that was not filled.

done

**Comment by olivergondza** [comment]
@bloom-repo, please be more specific about what the issue consequences are. #124 mentions "exception" and "problem", but none of that is elaborated on. Also, as indicated in the Submitter checklist, was this verified manually to work as expected (as unittest is clearly absent)?

**Comment by bloom-repo** [comment]
I just fix a bug. 
The testcase already in hub:  https://github.com/openstack4j/openstack4j/blob/master/core-test/src/main/java/org/openstack4j/api/network/NetQosPolicyTests.java#create

The error detail i just submitted.

**Comment by olivergondza** [comment]
> The testcase already in hub: https://github.com/openstack4j/openstack4j/blob/master/core-test/src/main/java/org/openstack4j/api/network/NetQosPolicyTests.java#create

There seem to be some misunderstanding here. The test you have linked was passing before and after your fix, so clearly it does not reproduce the issue at hand. Please submit a failing unittest that will get fixed as a result of your fix. This is important to verify it is actually efficient and demonstrate the nature of the problem. Thanks!

**Pull request closed without merging**
