### PR TITLE
Introduce Issue and PR templates

### PR DESCRIPTION
**Pull request by olivergondza**
Add templates for the PR and a first template for the issue creation. This is in order to make sure we get all information we need easily. GitHub seems to provide the issue template selection dialogue (so we can keep on adding further templates for frequently used issue types), but the UI only support single PR template.

This is how it works when deployed:

- https://github.com/olivergondza/openstack4j/compare/master...olivergondza:change
- https://github.com/olivergondza/openstack4j/issues/new/choose

@openstack4j/reviewers, PTAL. Hope you folks are enjoying holidays!

### CODE REVIEW

**Comment by pjdarton** [comment]
I think it's a good idea, but I think it's more important to have a template for a "I've got a problem" issue - issues where folks are trying to construct a bug report are likely to outnumber API enhancement requests, and more likely to require the kind of assistance that a template provides.
i.e. by all means have an API-issue template _as well_ but the first template to choose from in the list _must_ be for people who are trying to report a bug.

**Comment by olivergondza** [comment]
@pjdarton, good point. Albeit unpredictable, we want to provide some structure/guidance to those issues.

Would you like to draft the template?

**Comment by pjdarton** [comment]
Disclaimer: I'm not very familiar with how these github templates work...

First, I think we need to rename `.github/ISSUE_TEMPLATE/1api.md` to `.github/ISSUE_TEMPLATE/2api.md`

Then, I guess that we create a new file `.github/ISSUE_TEMPLATE/1bugreport.md` which says something like:
```
---
name: "Bug report"
about: "Something is failing to do what it is documented/expected to do."
---
<!--- Provide a one-line summary of the issue in the Title -->

## Current Behavior
<!--- Describe what actually happens -->
<!--- Describe when this happens -->
<!--- Include logs from https://your.jenkins.server/log/ if appropriate, especially if there are exceptions -->
<!--- Include screenshots from https://your.jenkins.server/ if it will help illustrate the issue, especially if this bug is regarding the Jenkins UI -->
<!--- Note: Redact any sensitive information before submitting -->

## Environment
<!--- Describe your working environment in which you encounter this issue -->
<!--- What version(s) of Jenkins does this issue affect? -->
<!--- What version(s) of this plugin does this affect? -->
<!--- What version(s) of OpenStack?  List individual module versions if you have a mixed setup. -->
<!--- How your Jenkins & OpenStack instance are connected/communicate -->
<!--- How your OpenStack instance is configured and being used in this case -->
<!--- If this is a regression and "it used to work fine", describe the environment where it used to work too. -->

## Impact
<!--- Describe what the real-world consequences are -->
<!--- What are you trying to achieve?  How does this interfere? -->
<!--- Describe what workarounds are necessary/possible -->

## Expected Behavior
<!--- Describe what should happen instead -->
<!--- If this bug is about the Jenkins UI then consider making a "how it ought to look" picture. -->

## Steps to Reproduce
<!--- Provide a step-by-step process to reproduce the issue -->
<!--- Note: In general, the easier it is to reproduce an issue, the easier it is to fix. -->
<!--- Assume that folks are starting with an empty Jenkins instance with this plugin installed -->

<!--- Note: Reports should be in English. -->
<!--- Hint: Screenshots, logs and stacktraces can help overcome language barriers (and other communication issues). -->
<!--- Disclaimer: Open-source software is primarily maintained by volunteers, collaborating for mutual benefit. If you make it easy for others to help you, it is more likely others will do so, but nobody is obliged to do so. -->
```

I _think_ that's what we need but, like I said, I'm not very familiar with how github templates work.

**Comment by olivergondza** [comment]
That is quite comprehensive, @pjdarton. Thanks!

Let me massage that a bit and make it a default template.

**Comment by pjdarton** [comment]
Looks good to me 👍

**Pull request merged**
