### PR TITLE
fix bug about update subnet.

### PR DESCRIPTION
**Pull request by bboyHan**
#87 fixed it

### CODE REVIEW

**Comment by olivergondza** [comment]
Please point out the REST API doc the document this. Provided this is truly causing incorrect request to be sent, it makes sense fixing.

**Comment by bboyHan** [comment]
Thanks for your reply.

https://docs.openstack.org/api-ref/network/v2/?expanded=update-subnet-detail#subnets

rest url:  PUT   /v2.0/subnets/{subnet_id} 

Description:  gateway_ip (Optional Parameter)

Gateway IP of this subnet. If the value is null that implies no gateway is associated with the subnet. If the gateway_ip is not specified, OpenStack Networking allocates an address from the CIDR for the gateway for the subnet by default.

**Comment by olivergondza** [comment]
Hmm, let me see if I understand OpenStack contract correctly:

- If the field is absent - OpenStack auto-allocates.
- If the field is `null` - No gateway is associated.
- Otherwise the value is used as gateway.

What you have found out is, that when the value is an empty string, it behaves as if `null` is passed (although this is undocumented by OpenStack) - No gateway is associated. I am wondering what effective change does this make, IIUC OpenStack should do the same thing, right?

However, we can do a better job preventing users to pass in invalid/undocumented values. Though I thing that a better place to capture that would be either where the data are sent or where they are accepted from users (builder).

Off topic: this have pointed out to me, we have no way to keep the value absent and excercise the auto-allocation.

**Comment by bboyHan** [comment]
Thanks for your reply. I understanded better than before in your explanation.

**Comment by bboyHan** [comment]
Thanks for your reply. I understanded better than before in your explanation.

**Pull request closed without merging**
